### ISSUE TITLE
Cannot transpose keywords

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/clojure-ts-mode#17]
## Expected behavior
Given a `.clj` file with the following content:
```clojure
{:a :b}
```
With point between `:a` and `:b`:
```clojure
{:a| :b}
```
If I hit <kbd>C-M-t</kbd>, I get:
```clojure
{:b :a}
```
Just like `clojure-mode` behaves.

## Actual behavior
Given the previous scenario, when I hit <kbd>C-M-t</kbd>, I get the message:
```
transpose-subr-1: Don’t have two things to transpose
```

## Steps to reproduce the problem

Provided `clojure-ts-mode` is installed (I installed via NonGNU ELPA):

- `emacs -Q`
- <kbd>M-x package-initialize RET</kbd>
- <kbd>C-x C-f /tmp/test.clj RET</kbd>
- <kbd>M-x clojure-ts-mode RET</kbd> (thanks @sogaiu for noticing I missed this step)
- Write `{:a :b}`
- Place cursor between `:a` and `:b`
- Hit <kbd>C-M-t</kbd>

### clojure-ts-mode version
```
0.1.4
```

### Emacs version

GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, cairo version 1.16.0) of 2023-08-29

### Operating system

Ubuntu 22.04.3

**Comment by sogaiu** [comment]
In my case transposition does occur without issues with the following bits:

* clojure-ts-mode (d630cd63)
* Emacs 29.1.50 (built from source, not sure of commit, but around 2023-08-09)
* Ubuntu 22.04.3

I'll see if I can reproduce with bits closer to the original report.

**Comment by sogaiu** [comment]
Still no reproduction (transposition happens) using:

* clojure-ts-mode (0.1.4 from Non-GNU Elpa -- used M-x package-install)
* Emacs 29.1.50 (built from source, f26622b2 2023-08-28)
* emacs -Q
* M-x package-initialize
* C-x C-f /tmp/test.clj RET
* Put {:a :b} as buffer content
* M-x clojure-ts-mode (not doing this leaves me in fundamental mode, though no issue there either)
* Place cursor between :a and :b
* Enter C-M-t

**Comment by sogaiu** [comment]
I compared the source of `transpose-sexps` from 29.x and 30.y.

29.x:
```emacs-lisp
(defun transpose-sexps (arg &optional interactive)
  "Like \\[transpose-chars] (`transpose-chars'), but applies to sexps.
Unlike `transpose-words', point must be between the two sexps and not
in the middle of a sexp to be transposed.
With non-zero prefix arg ARG, effect is to take the sexp before point
and drag it forward past ARG other sexps (backward if ARG is negative).
If ARG is zero, the sexps ending at or after point and at or after mark
are interchanged.
If INTERACTIVE is non-nil, as it is interactively,
report errors as appropriate for this kind of usage."
  (interactive "*p\nd")
  (if interactive
      (condition-case nil
          (transpose-sexps arg nil)
        (scan-error (user-error "Not between two complete sexps")))
    (transpose-subr
     (lambda (arg)
       ;; Here we should try to simulate the behavior of
       ;; (cons (progn (forward-sexp x) (point))
       ;;       (progn (forward-sexp (- x)) (point)))
       ;; Except that we don't want to rely on the second forward-sexp
       ;; putting us back to where we want to be, since forward-sexp-function
       ;; might do funny things like infix-precedence.
       (if (if (> arg 0)
	       (looking-at "\\sw\\|\\s_")
	     (and (not (bobp))
		  (save-excursion
                    (forward-char -1)
                    (looking-at "\\sw\\|\\s_"))))
	   ;; Jumping over a symbol.  We might be inside it, mind you.
	   (progn (funcall (if (> arg 0)
			       'skip-syntax-backward 'skip-syntax-forward)
			   "w_")
		  (cons (save-excursion (forward-sexp arg) (point)) (point)))
         ;; Otherwise, we're between sexps.  Take a step back before jumping
         ;; to make sure we'll obey the same precedence no matter which
         ;; direction we're going.
         (funcall (if (> arg 0) 'skip-syntax-backward 'skip-syntax-forward)
                  " .")
         (cons (save-excursion (forward-sexp arg) (point))
	       (progn (while (or (forward-comment (if (> arg 0) 1 -1))
			         (not (zerop (funcall (if (> arg 0)
							  'skip-syntax-forward
						        'skip-syntax-backward)
						      ".")))))
		      (point)))))
     arg 'special)))
```

30.y:
```emacs-lisp
(defun transpose-sexps (arg &optional interactive)
  "Like \\[transpose-chars] (`transpose-chars'), but applies to sexps.          
Unlike `transpose-words', point must be between the two sexps and not           
in the middle of a sexp to be transposed.                                       
With non-zero prefix arg ARG, effect is to take the sexp before point           
and drag it forward past ARG other sexps (backward if ARG is negative).         
If ARG is zero, the sexps ending at or after point and at or after mark         
are interchanged.                                                               
If INTERACTIVE is non-nil, as it is interactively,                              
report errors as appropriate for this kind of usage."
  (interactive "*p\nd")
  (if interactive
      (condition-case nil
          (transpose-sexps arg nil)
        (scan-error (user-error "Not between two complete sexps")))
    (transpose-subr transpose-sexps-function arg 'special)))
```

**Comment by sogaiu** [comment]
I am not sure yet actually.

I'm not sure the `treesit-transpose-sexps` implementation is reasonable.  It seems to be assuming that `(treesit-node-at (point))` will yield an appropriate node for what it wants to accomplish.  For tree-sitter-clojure's case, it is looking too deeply for keywords and symbols.

IIUC, there are over 300 tree-sitter grammars and I wonder whether tree-sitter-clojure is the only one that has this sort of characteristic.

**Comment by sogaiu** [comment]
No worries!

Thanks for opening this issue -- I think it's often better to learn of these things earlier rather than later :)

**Comment by sogaiu** [comment]
I tried the changes with Emacs 30.y (88bb7cdf) and it worked fine here.

---

I think it might be worth bringing this up with the Emacs devs -- at least @casouri.  With the number of grammars in existence, it doesn't seem unlikely to me that others might encounter this issue.

I don't know if it's a good idea, but possibly each `*-ts-mode` could enumerate which nodes don't work so well with `treesit-transpose-sexps`'s current algorithm in some manner and this information could be made use of by `treesit-transpose-sexps` to adjust.

It might make sense to do something like the above (enumerate "exceptions") as I don't know that transposition is going to be the only thing affected by: 

> if tree-sitter would have properly parsed keyword names and namespaces into fields of anonymous nodes instead of forcing us to resort to named nodes

It seems possible other structural editing types of operations might encounter issues as well.

**Comment by sogaiu** [comment]
I wonder if the types of changes we've been discussing [here](https://github.com/sogaiu/tree-sitter-clojure/issues/52) about string and regex nodes having internal "structure" would also lead to similar issues...

**Comment by casouri** [comment]
I didn't write `treesit-transpose-sexps`, but I've got some good news. Theo (@ theothornhill) added `treesit-sexp-type-regexp` in Emacs 30 which allows some customization, but I guess `treesit-transpose-sexps` wasn't updated to take advantage of it, or there was some other reason. Not long ago I added `treesit-node-match-p` and `treesit-thing-settings` and friends, which allows one to flexibly define "things", so this should be possible:

>I don't know if it's a good idea, but possibly each *-ts-mode could enumerate which nodes don't work so well with treesit-transpose-sexps's current algorithm in some manner (i.e. kwd_name is too deep, kwd_lit is the desired node) and this information could be made use of by treesit-transpose-sexps to adjust.

I think what I'll do is retire `treesit-sexp-type-regexp` (since `treesit-thing-settings` can replace it), and make `treesit-forward/backward-sexp` and `treesit-transpose-sexps` take advantage of `treesit-thing-settings`. Then you can see if that'll allow you to make a better transpose-sexp experience.

> I also think it would be worth brining this transpose issue to the emacs devs. I may do so soon, but need to take a little break from the mailing list first.

You have my condolence. FWIW, I think the people who actually put in the time and effort to maintain a project obviously have the right to decide what works for them and how they want to work. It's the same for Emacs devs who don't want to move to a forge until all their needs are met; and the same for Clojure-mode devs who want to maintain Clojure-mode outside of Emacs and not ask for assignments.

I was going to join the discussion with my 2c, but the further down I read the thread, the more my motivation dwindles ;-)

**Comment by casouri** [comment]
To give some context, there was some discussion about supporting extending structural movement/editing functions with tree-sitter, which includes `forward/backward-sexp` and `transpose-sexp`, and perhaps a couple more. For Emacs 29, I managed to get movement function for defuns implemented. But the rest has to wait for Emacs 30.

The problem was what does sexp means in a tree-sitter major mode. The idea of Stefan and Theo was that the sexp would be determined by the position of point. Eg, something like "the largest/smallest node before/after point".

Personally I'm more fond of defining sexps as "repeatable nodes", ie, any node that can be repeated in the grammar. So things like defun, arguments in an argument, statements, list elements, etc, are all considered sexps. This is more straightforward (ie, lower cognitive load) and useful for movement, IMO.

But my idea is perhaps more suitable for `forward/backward-list`. Anyway, we went with sexp = syntax construct at point.

I hope this explains the particular way `treesit-transpose-sexps` is implemented. Theo can probably explain it better since he wrote it.

**Comment by casouri** [comment]
> Thanks for chiming in with this. I'll try to keep an eye out for those changes and see about filling out the treesit-thing-settings in the meantime.

I just pushed a change to master. Now `treesit-transpose-sexps` should work with `treesit-thing-settings`. It should find the sexp at point and transpose it with its siblings.

**Comment by sogaiu** [comment]
@casouri Thanks for the heads up.

@dannyfreeman For reference, here are some `treesit-thing-settings` examples I came across:

`sentence`

* [dockerfile-ts-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/dockerfile-ts-mode.el#L178-L180)
* [json-ts-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/json-ts-mode.el#L150-L152)
* [sh-script.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/sh-script.el#L1632-L1636)

`sexp`

* [ruby-ts-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/ruby-ts-mode.el#L1125-L1163)

`text`

* [csharp-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/csharp-mode.el#L962-L967)
* [heex-ts-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/heex-ts-mode.el#L152-L154)

`sentence`, `sexp`, `text`

* [c-ts-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/c-ts-mode.el#L1133-L1159)
* [js.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/js.el#L3896-L3901)
* [typescript-ts-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/typescript-ts-mode.el#L437-L443)

**Comment by sogaiu** [comment]
[Here](https://github.com/emacs-mirror/emacs/blob/c640e978874385f9774c2903b97677406bee97a2/src/treesit.c#L4008-L4032) are recent docs for `treesit-thing-settings`:

```c
  DEFVAR_LISP ("treesit-thing-settings",
	       Vtreesit_thing_settings,
	       doc:
	       /* A list defining things.

The value should be an alist of (LANGUAGE . DEFINITIONS), where
LANGUAGE is a language symbol, and DEFINITIONS is a list of

    (THING PRED)

THING is a symbol representing the thing, like `defun', `sexp', or
`sentence'; PRED defines what kind of node can be qualified as THING.

PRED can be a regexp string that matches the type of the node; it can
be a predicate function that takes the node as the sole argument and
returns t if the node is the thing, and nil otherwise; it can be a
cons (REGEXP . FN), which is a combination of a regexp and a predicate
function, and the node has to match both to qualify as the thing.

PRED can also be recursively defined.  It can be (or PRED...), meaning
satisfying anyone of the inner PREDs qualifies the node; or (not
PRED), meaning not satisfying the inner PRED qualifies the node.

Finally, PRED can refer to other THINGs defined in this list by using
the symbol of that THING.  For example, (or sexp sentence).  */);
```

FWIW, I didn't find any examples where `PRED` was a predicate function and my brief tinkering didn't yield useful results (likely pilot error and lack of understanding (^^; ).

**Comment by sogaiu** [comment]
@casouri I tried a variety of things without much success (see below for my best guess).

I also tried with some JavaScript:

```javascript
var a = [true, false];
//            ^
//            |
//          cursor
```

Using `js-ts-mode`, the result of `C-M-t` was:

```javascript
var [true, false] = a;
```

When not using `js-ts-mode`, the expected result appeared:

```javascript
var a = [false, true];
```

So may be it's possible there's something not quite right?

I think the emacs I tried was from the master branch at commit 781c0393.

---

What I thought might work for `clojure-ts-mode` was:

```diff
diff --git a/clojure-ts-mode.el b/clojure-ts-mode.el
index 2fc9a4a..f235f5c 100644
--- a/clojure-ts-mode.el
+++ b/clojure-ts-mode.el
@@ -618,7 +618,35 @@ See `clojure-ts--standard-definition-node-name' for the implementation used.")
                 treesit-font-lock-feature-list
                 '((comment string char number)
                   (keyword constant symbol bracket builtin)
-                  (deref quote metadata definition variable type doc regex tagged-literals)))
+                  (deref quote metadata definition variable type doc regex tagged-literals))
+                treesit-thing-settings
+                `((clojure
+                   (sexp ,(regexp-opt '("#_"
+                                        "num_lit"
+                                        "kwd_lit"
+                                        "str_lit"
+                                        "char_lit"
+                                        "nil_lit"
+                                        "bool_lit"
+                                        "sym_lit"
+                                        "list_lit"
+                                        "map_lit"
+                                        "vec_lit"
+                                        "set_lit"
+                                        "anon_fn_lit"
+                                        "regex_lit"
+                                        "read_cond_lit"
+                                        "splicing_read_cond_lit"
+                                        "ns_map_lit"
+                                        "var_quoting_lit"
+                                        "sym_val_lit"
+                                        "evaling_lit"
+                                        "tagged_or_ctor_lit"
+                                        "derefing_lit"
+                                        "quoting_lit"
+                                        "syn_quoting_lit"
+                                        "unquote_splicing_lit"
+                                        "unquoting_lit"))))))
     (when clojure-ts--debug
       (setq-local treesit--indent-verbose t
                   treesit--font-lock-verbose t)
```

---

@dannyfreeman On a side note, I included `#_`, because IIUC, it's a convenient thing to be able to toggle between two parameters, e.g. between:

```clojure
(my-nice-fn left-alt #_ right-alt)
```

```clojure
(my-nice-fn #_ left-alt right-alt)
```

**Comment by sogaiu** [comment]
> missing a layer of parens

```emacs-lisp
`((clojure 
   ( ;; right here
     (sexp ;; ...
```

Puzzling because AFAICT the samples I found don't seem to have a paren there...

For example in [ruby-ts-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/ruby-ts-mode.el#L1125-L1163):

```emacs-lisp
  (setq-local treesit-thing-settings
              `((ruby
                 (sexp ,(cons (rx
```

or in [c-ts-mode.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/c-ts-mode.el#L1133-L1159):

```emacs-lisp
  (setq-local treesit-thing-settings
              `((c
                 ;; It's more useful to include semicolons as sexp so
                 ;; that users can move to the end of a statement.
                 (sexp (not ,(rx (or "{" "}" "[" "]" "(" ")" ","))))
```

or in [js.el](https://github.com/emacs-mirror/emacs/blob/6880ea7d2280968014603ad23f753fa50f345c76/lisp/progmodes/js.el#L3896-L3901):

```emacs-lisp
    (setq-local treesit-thing-settings
                `((javascript
                   (sexp ,(regexp-opt js--treesit-sexp-nodes)))
```

The docstring I looked at had:

```
The value should be an alist of (LANGUAGE . DEFINITIONS), where
LANGUAGE is a language symbol, and DEFINITIONS is a list of

    (THING PRED)
```

With `(LANGUAGE . DEFINITIONS)` being a cons, isn't:

```emacs-lisp
(LANGUAGE . ((THING PRED) (THING PRED) ...))
```

the same as:

```emacs-lisp
(LANGUAGE (THING PRED) (THING PRED) ...)
```

?

May be there's some disconnect among the mode code, the docstring, and the implementation...or may be I've just missed something obvious (^^;

**Comment by sogaiu** [comment]
Will need to digest the precedence stuff.  Seems potentially tricky.

---

I think I may have learned the transposition of `#_` trick for argument toggling from @PEZ when doing a small amount of work on calva, so can't claim any credit there :)

**Comment by casouri** [comment]
Most likely Danny didn't set `treesit-thing-settings` correctly and Emacs falls back to using the default sexp function, which observes the same behavior as `clojure-mode` ;-) I need to look at the definition of `treesit-transpose-sexps`. It seems that simply adding `treesit-thing-settings` support to it doesn't solve the problem. I might need to change its logic or rewrite it.

**Comment by sogaiu** [comment]
@casouri Thanks for taking a look!

Just to clarify, do you observe the same behavior for the JavaScript example [mentioned here](https://github.com/clojure-emacs/clojure-ts-mode/issues/17#issuecomment-1704291492)?  Repeating below for convenience:

```javascript
var a = [true, false];
//            ^
//            |
//          cursor
```

Using js-ts-mode, the result of C-M-t was:

```javascript
var [true, false] = a;
```

When not using js-ts-mode, the expected result appeared:

```javascript
var a = [false, true];
```

**Comment by sogaiu** [comment]
@manuel-uberti Note this [potential caveat](https://github.com/clojure-emacs/clojure-ts-mode/issues/17#issuecomment-1705699794) though.
