### ISSUE TITLE
Syntax highlighting problem (?), can someone reproduce this. 

### ISSUE THREAD

**Issue by jasonjckn** [clojure-emacs/clojure-ts-mode#24]
## Expected behavior
<img width="868" alt="image" src="https://github.com/clojure-emacs/clojure-ts-mode/assets/550839/252a9bab-2436-417e-8e15-9e5de7bba8a7">

## Actual behavior
<img width="880" alt="image" src="https://github.com/clojure-emacs/clojure-ts-mode/assets/550839/5f983327-8bda-40fa-af43-97a739f951f0">

## Steps to reproduce the problem

Hopefully someone can reproduce this easily, if not, just close this issue . My emacs config is pretty complex, so it could be easily something else. 

copy and paste this at the top of a large clojure file without any other backticks , and you see syntax color mess up 

```
(defmacro satisfies? [c]
  {:pre [(symbol? c)
         (contains? (eval c) :on)]}
  `[:fn {:error/message (str "should satisfy protocol " (:on ~c))}
    #(clojure.core/satisfies? ~c %)])
``` 

### clojure-ts-mode version

*Include here the version string displayed by `M-x
clojure-ts-mode-display-version`. Here's an example:*
<img width="320" alt="image" src="https://github.com/clojure-emacs/clojure-ts-mode/assets/550839/7b4b8a02-fc86-4a00-adcc-e35e6d514f98">
i'm on a fork... maybe that's why. but its very recent. 

```
clojure-ts-mode (version 0.1.5)
```

### tree-sitter-clojure grammar version

*E.g. v0.0.12*
should be the latest, its rarely updated. 

*Please make sure you are using compatible tree-sitter grammars.
See the variable clojure-ts-grammar-recipes for the current recommend versions.
They should be installed automatically if not found.
However, some linux distributions package these same grammars and Emacs will use them if found.*

**If you are not sure what version you are using, try running
M-x treesit-install-language-grammar <RET> clojure <RET> y, and use the values
https://github.com/sogaiu/tree-sitter-clojure.git for the URL,
v0.0.12 for the TAG and default values for the remaining options.
Then see if the problem still persists.**

### Emacs version

*29.1* 
using the emacs-mac build from https://github.com/railwaycat/homebrew-emacsmacport

### Operating system

mac

**Comment by sogaiu** [comment]
The following is what I get when I put the sample of code at the beginning of clojure's `core.clj` (with backticks removed):

![clojure-ts-mode-issue-24](https://github.com/clojure-emacs/clojure-ts-mode/assets/33044872/d3fed679-8ea0-4290-8910-c87dbe2cf0b8)

This is with emacs 29.1 and clojure-ts-mode 8e61fe8f (0.2.0).

**Comment by jasonjckn** [comment]
Thanks everyone, going to close this and take a deeper dive on the weekend, reopen if needed. Sounds like its on my end.
