### ISSUE TITLE
tree-sitter shows jit-lock-function error when i delete some code 

### ISSUE THREAD

**Issue by vinurs** [clojure-emacs/clojure-ts-mode#52]
Hi,

I am using the latest emacs-30 https://github.com/emacs-mirror/emacs/commit/81347c1aaf25b27e78e8beee4bc818ad2c4e1b71

The min configuration is as follows:

(add-to-list 'treesit-extra-load-path (expand-file-name "tree-sitter/" user-emacs-directory))

(add-to-list 'load-path "~/.emacs.d/site-lisp/clojure-ts-mode”)

(require 'clojure-ts-mode)

;; debug

(setq debug-on-quit t)

and I only use clojure-ts-mode package

cd ~/.emacs.d/site-lisp

git clone https://github.com/clojure-emacs/clojure-ts-mode.git

Then, after opening Emacs, Open the elong.clj file, go to line 115, select the entire build-inventory-check-failure-response function, and then delete this function. You'll notice that the remaining code is no longer highlighted. Then I found the following error output in the Message buffer:

Error during redisplay: (jit-lock-function 4221) signaled (wrong-type-argument number-or-marker-p nil) [2 times

![elong-1](https://github.com/user-attachments/assets/604ee823-af7f-4133-b242-63bdd7859364)
![elong-2](https://github.com/user-attachments/assets/8bb980eb-d68a-4a56-9557-3517f50465b2)

[elong.clj.txt](https://github.com/user-attachments/files/17004881/elong.clj.txt)

**Comment by sogaiu** [comment]
I don't know if I followed the instructions correctly (except for the Emacs version), but with Emacs 29.3, I didn't observe any error message in the `*Messages*` buffer, nor was there an issue with highlighting [1].

---

[1] Scrolling up and down a bit from the point where deletion occurred didn't turn up any unhighlighted areas.

**Comment by vinurs** [comment]
it's a emacs bug 
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=73264

**Comment by vinurs** [comment]
fixed https://github.com/emacs-mirror/emacs/commit/460b9d705ab482003fabe75b0fd1df223abe467c
